name: Fetch Instagram Engagement

on:
  schedule:
    - cron: '0 13 * * *' # every day at 13:00 UTC
  workflow_dispatch:    # allows manual runs if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: node src/index.js
        env:
            INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
            INSTAGRAM_MAIN_ID: ${{ secrets.INSTAGRAM_MAIN_ID }}
            OVERWATCH_ID: ${{ secrets.OVERWATCH_ID }}
            SPLATOON_ID: ${{ secrets.SPLATOON_ID }}
            VALORANT_ID: ${{ secrets.VALORANT_ID }}
            TEKKEN_ID: ${{ secrets.TEKKEN_ID }}
            MARVELRIVALS_ID: ${{ secrets.MARVELRIVALS_ID }}
            COUNTERSTRIKE_ID: ${{ secrets.COUNTERSTRIKE_ID }}
            STREETFIGHTER_ID: ${{ secrets.STREETFIGHTER_ID }}
            FORTNITE_ID: ${{ secrets.FORTNITE_ID }}
            SMASH_ID: ${{ secrets.SMASH_ID }}
            LEAGUEOFLEGENDS_ID: ${{ secrets.LEAGUEOFLEGENDS_ID }}
            RAINBOWSIXSIEGE_ID: ${{ secrets.RAINBOWSIXSIEGE_ID }}
            ROCKETLEAGUE_ID: ${{ secrets.ROCKETLEAGUE_ID }}
            GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
            SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
            GOOGLE_CLIENT_EMAIL: ${{secrets.GOOGLE_CLIENT_EMAIL}}
            GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}
